### ISSUE TITLE
查詢問題，中文查詢"分"列出10個單詞

### ISSUE THREAD

**Issue by ss1111119** [miaoski/amis-linebot#2]
有「分」的阿美語詞
1. licinowas
2. pakilac
3. marifowas
4. laliping
5. milakelak
6. mipela'
7. kanikaran
8. liyas
9. 'isal
10. cawi'

回傳9時

出現"找不到這個詞。"

但在阿美語萌典時可以查詢到 'isal單詞

謝謝

**Comment by miaoski** [comment]
Fixed by c32b86afe82a2cc46680f97033d228881bbccae0
