### ISSUE TITLE
查詢問題，中文查詢"熱"列出10個單詞

### ISSUE THREAD

**Issue by ss1111119** [miaoski/amis-linebot#3]
有「熱」的阿美語詞
1. tahod
2. ngohngoh
3. fa'det
4. ciferang
5. fadat
6. 'adipangpang
7. kofing
8. 'nged
9. alaf^af
10. fala^fa

第6,8都查不到單詞

謝謝

**Comment by miaoski** [comment]
Fixed by c32b86afe82a2cc46680f97033d228881bbccae0
